# Site settings
title: Wunderline. Wunderlist for your command line!
email: hello@wearenext.co.za
description: Get stuff done with Wunderlist and your command line.
baseurl: "http://wayneashleyberry.github.io/wunderline/"
url: "http://wayneashleyberry.github.io/wunderline/"
github_username: wayneashleyberry
google_analytics: UA-64418678-1
twitter_username: nextct

# Build settings
exclude: ['node_modules', 'Gruntfile.js', 'README.md', 'CNAME', 'package.json']
markdown: kramdown
sass:
    style: :compressed
