# Site settings
title: Wunderline. Wunderlist for your command line!
email: hello@wearenext.co.za
description: Get stuff done with Wunderlist and your command line.
baseurl: ""
url: "http://www.wunderline.rocks"
twitter_username: nextct
github_username: we-are-next
google_analytics: UA-64418678-1

# Build settings
markdown: kramdown
sass:
    style: :compressed
