# Site settings
title: Wunderline
email: info@wunderline.rocks
description: Wunderlist for your command line!
baseurl: "/wunderline"
url: "http://www.wunderline.rocks"
twitter_username: nextct
github_username: we-are-next

# Build settings
markdown: kramdown
highlighter: null
sass:
    style: :compressed
