# Site settings
title: Wunderline
email: hello@wearenext.co.za
description: Wunderlist for your command line!
baseurl: ""
url: "http://www.wunderline.rocks"
twitter_username: nextct
github_username: we-are-next
google_analytics: UA-64418678-1

# Build settings
markdown: kramdown
sass:
    style: :compressed
