# Site settings
title: Wunderline
email: info@wunderline.rocks
description: Wunderlist for your command line!
baseurl: ""
url: "http://www.wunderline.rocks"
twitter_username: nextct
github_username: we-are-next
google_analytics: UA-64418678-1

# Build settings
markdown: kramdown
# highlighter: null
sass:
    style: :compressed
