# Site settings
title: Wunderline
email: info@wunderline.com
description: Wunderlist for your command line!
baseurl: ""
url: "http://www.wunderline.com"
twitter_username: nextct
github_username: we-are-next

# Build settings
markdown: kramdown
# highlighter: null
sass:
    style: :compressed
